input_data_path: "data/test_data_sample.csv"
predictons_path: "models/predictions.csv"
transformer_path: "models/transformer_lr.pkl"
model_path: "models/model.pkl"
feature_params:
  categorical_features:
    - "STDs:vaginal condylomatosis"
    - "STDs:syphilis"
    - "STDs:pelvic inflammatory disease"
    - "STDs:genital herpes"
    - "STDs:molluscum contagiosum"
    - "STDs:HIV"
    - "STDs:Hepatitis B"
    - "STDs:HPV"
    - "STDs:cervical condylomatosis"
    - "STDs:AIDS"
    - "Dx:Cancer"
    - "Dx:CIN"
    - "Dx:HPV"
    - "Dx"
    - "Smokes"
    - "IUD"
    - "Hormonal Contraceptives"
    - "STDs"
    - "STDs:condylomatosis"
    - "STDs:vulvo-perineal condylomatosis"
  numerical_features:
    - "Number of sexual partners"
    - "First sexual intercourse"
    - "Num of pregnancies"
    - "Age"
    - "Smokes (packs/year)"
    - "Smokes (years)"
    - "Hormonal Contraceptives (years)"
    - "IUD (years)"
    - "STDs: Time since first diagnosis"
    - "STDs: Time since last diagnosis"
    - "STDs: Number of diagnosis"
    - "STDs (number)"
  features_to_drop:
    - "Citology"
    - "Hinselmann"
    - "Schiller"
  target_col: "Biopsy"