# @package _group_
model_type: "KerasSimpleNN"
random_state: 0
first_layer:
  units: 500
  input_dim: 50
  kernel_initializer: "uniform"
  activation: "relu"
second_layer:
  units: 200
  kernel_initializer: "uniform"
  activation: "relu"
output_layer:
  units: 1
  kernel_initializer: "uniform"
  activation: "sigmoid"
dropout: 0.5
compile:
  loss: 'binary_crossentropy'
  optimizer: 'adam'
  metrics: 'AUC'
train:
  epochs: 20
  batch_size: 200
  verbose: 2
