apiVersion: v1
kind: Pod
metadata:
  name: online-inference-pod-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: vkorennoy/online_inference:v11
      name: online-inference
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 15
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 15
        failureThreshold: 10
