apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: vkorennoy/online_inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
